knpu_oauth2_client:
  clients:
    keycloak:
      type: keycloak
      auth_server_url: '%oidc_issuer%'
      realm: '%oidc_realm%'
      client_id: '%oidc_client_id%'
      redirect_route: 'oauth_check'
      client_secret: '%oidc_client_secret%'