monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: grouped
        grouped:
            type: group
            # members: [file, mattermost, deduplicated]
            members: [file, mattermost]
        file:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
        mattermost:
            type: slackwebhook
            webhook_url: "%logging.mattermost.url%"
            channel: '%logging.mattermost.channel%'
            bot_name: 'Monolog'
            use_attachment: true,
            icon_emoji: ''
            use_short_attachment: true
            include_extra: true
            level: '%logging.mattermost.level%'
        # Avoid getting spammed multiple times by the same exception
        # deduplicated:
        #     type: deduplication
        #     time: 20
        #     handler: mailer
